# Generated by Django 5.0.7 on 2024-08-13 06:49

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='static/category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='static/previews'),
        ),
    ]
