# Generated by Django 5.0.7 on 2024-08-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_cartproducts_order_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
