# Generated by Django 5.0.7 on 2024-08-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cartproducts_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproducts',
            old_name='count',
            new_name='quantity',
        ),
    ]
