# Generated by Django 5.1 on 2024-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart_created_date_cart_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hitcount',
            field=models.IntegerField(default=0),
        ),
    ]
