# Generated by Django 5.1 on 2024-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
